name: Python package

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: LS
      run: |
        ls
    - name: PWD
      run: |
        pwd
    - name: Lint with flake8
      run: |
        python3 -m flake8 . --max-line-length=120
